apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc

spec:
  replicas: 2
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        zone: prod
        version: v1
    spec:
      containers:
      - name: hello-ctr
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080
    
